### PR TITLE
feat: added product sorting & filtering to the product listing page

### PR DESCRIPTION
**Pull request by ChhikaraBRUH**
Added sorting and filtering functionality to the product listing page.
Also Clear button clears and resets all the filters to initial state.

**Visit this and then scroll down and click any of the 3 "CHECK IT OUT" Buttons for Preview:**
https://deploy-preview-2--snkrs-store.netlify.app/

### CODE REVIEW

**Review by Abhijeet43 — CHANGES_REQUESTED** [review]
Hey Chaitanya, Please provide a seperate scroll bar for your filters section... As it is making some categories inaccessible currently

**Comment by ChhikaraBRUH** [comment]
working on it

**Comment by ChhikaraBRUH** [comment]
done @Abhijeet43 
can you please approve?

**Review by k-rahul21 — APPROVED** [review]

**Comment by k-rahul21** [comment]
The code looks good to me.
Ready to merge.

**Review by Meghana-sk — APPROVED** [review]
Good job Chaitanya. UI looks good and functionality is proper

**Pull request merged**
